[package]
name = "rspulse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-binding = "2.27"
libpulse-sys = "1.20.1"
paste = "1.0.12"
quote = "1.0.26"
